### ISSUE TITLE
关于“换行“文字错位问题

### ISSUE THREAD

**Issue by ghost** [JackuXL/WearNote#3]
# 关于“换行“文字错位问题
## 系统信息
> 手表版本：小天才Z7 2.0.6_1944_230310
> 系统版本：Android8.1.0,CaremeOS1.0
> 手表型号W2025AC
## 问题描述
> 换行文字（有几率）错位
图片文件：https://pan.huang1111.cn/s/qm5yu3

**Comment by JackuXL** [comment]
已修复，谢谢反馈。
